package com.foodwasteai.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Model representing detailed food-by-food prediction items generated by SWI-Prolog reasoning.
 */
public class PredictionItem implements Serializable {
    private static final long serialVersionUID = 1L;

    public enum RiskLevel {
        LOW,
        MEDIUM,
        HIGH
    }

    private Long id;
    private Long predictionId;
    private Long foodItemId;
    private String foodItemName; // Joined
    private String unit = "kg"; // Joined from food_items
    private BigDecimal currentStock;
    private BigDecimal expectedDemand;
    private Integer expiryDays;
    private BigDecimal historicalWasteRate;
    private RiskLevel riskLevel;
    private BigDecimal riskPercentage;
    private BigDecimal riskScore; // Alias synced with riskPercentage
    private BigDecimal predictedWasteQty;
    private BigDecimal predictedWasteQuantity; // Alias
    private BigDecimal recommendedProduction;
    private String priorityUsage;
    private String reasoningText;
    private String reasoningTextEn;
    private String reasoningTextMy;
    private LocalDateTime createdAt;

    public PredictionItem() {}

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPredictionId() {
        return predictionId;
    }

    public void setPredictionId(Long predictionId) {
        this.predictionId = predictionId;
    }

    public Long getFoodItemId() {
        return foodItemId;
    }

    public void setFoodItemId(Long foodItemId) {
        this.foodItemId = foodItemId;
    }

    public String getFoodItemName() {
        return foodItemName;
    }

    public void setFoodItemName(String foodItemName) {
        this.foodItemName = foodItemName;
    }

    public String getUnit() {
        return unit != null ? unit : "kg";
    }

    public void setUnit(String unit) {
        this.unit = unit != null ? unit.trim() : "kg";
    }

    public BigDecimal getCurrentStock() {
        return currentStock;
    }

    public void setCurrentStock(BigDecimal currentStock) {
        this.currentStock = currentStock;
    }

    public BigDecimal getExpectedDemand() {
        return expectedDemand;
    }

    public void setExpectedDemand(BigDecimal expectedDemand) {
        this.expectedDemand = expectedDemand;
    }

    public Integer getExpiryDays() {
        return expiryDays;
    }

    public void setExpiryDays(Integer expiryDays) {
        this.expiryDays = expiryDays;
    }

    public BigDecimal getHistoricalWasteRate() {
        return historicalWasteRate;
    }

    public void setHistoricalWasteRate(BigDecimal historicalWasteRate) {
        this.historicalWasteRate = historicalWasteRate;
    }

    public RiskLevel getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(RiskLevel riskLevel) {
        this.riskLevel = riskLevel;
    }

    public BigDecimal getRiskPercentage() {
        return riskPercentage != null ? riskPercentage : riskScore;
    }

    public void setRiskPercentage(BigDecimal riskPercentage) {
        this.riskPercentage = riskPercentage;
        this.riskScore = riskPercentage;
    }

    public BigDecimal getRiskScore() {
        return riskPercentage != null ? riskPercentage : riskScore;
    }

    public void setRiskScore(BigDecimal riskScore) {
        this.riskScore = riskScore;
        this.riskPercentage = riskScore;
    }

    public BigDecimal getPredictedWasteQty() {
        return predictedWasteQty != null ? predictedWasteQty : predictedWasteQuantity;
    }

    public void setPredictedWasteQty(BigDecimal predictedWasteQty) {
        this.predictedWasteQty = predictedWasteQty;
        this.predictedWasteQuantity = predictedWasteQty;
    }

    public BigDecimal getPredictedWasteQuantity() {
        return getPredictedWasteQty();
    }

    public void setPredictedWasteQuantity(BigDecimal predictedWasteQuantity) {
        setPredictedWasteQty(predictedWasteQuantity);
    }

    public BigDecimal getRecommendedProduction() {
        return recommendedProduction;
    }

    public void setRecommendedProduction(BigDecimal recommendedProduction) {
        this.recommendedProduction = recommendedProduction;
    }

    public String getPriorityUsage() {
        return priorityUsage;
    }

    public void setPriorityUsage(String priorityUsage) {
        this.priorityUsage = priorityUsage;
    }

    public String getReasoningText() {
        return reasoningText;
    }

    public void setReasoningText(String reasoningText) {
        this.reasoningText = reasoningText;
        if (this.reasoningTextEn == null) {
            this.reasoningTextEn = reasoningText;
        }
    }

    public String getReasoningTextEn() {
        return reasoningTextEn != null ? reasoningTextEn : reasoningText;
    }

    public void setReasoningTextEn(String reasoningTextEn) {
        this.reasoningTextEn = reasoningTextEn;
    }

    public String getReasoningTextMy() {
        return reasoningTextMy;
    }

    public void setReasoningTextMy(String reasoningTextMy) {
        this.reasoningTextMy = reasoningTextMy;
    }

    public String getReasoningText(String lang) {
        if ("mm".equalsIgnoreCase(lang) || "my".equalsIgnoreCase(lang)) {
            return (reasoningTextMy != null && !reasoningTextMy.isEmpty()) ? reasoningTextMy : getReasoningTextEn();
        }
        return getReasoningTextEn();
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
