package com.foodwasteai.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Model representing actionable mitigation recommendations generated by SWI-Prolog expert system.
 */
public class Recommendation implements Serializable {
    private static final long serialVersionUID = 1L;

    public enum Category {
        URGENT,
        IMPORTANT,
        OPTIMIZATION,
        REDISTRIBUTION
    }

    public enum RiskLevel {
        LOW,
        MEDIUM,
        HIGH
    }

    public enum Status {
        PENDING,
        ACCEPTED,
        DISMISSED,
        COMPLETED
    }

    private Long id;
    private Long foodItemId;
    private String foodItemName; // Joined
    private Category category;
    private RiskLevel riskLevel;
    private String title;
    private String titleEn;
    private String titleMy;
    private String description;
    private String descriptionEn;
    private String descriptionMy;
    private String reasoningDetails;
    private String reasoningDetailsEn;
    private String reasoningDetailsMy;
    private BigDecimal estimatedSavings;
    private Status status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Recommendation() {}

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFoodItemId() {
        return foodItemId;
    }

    public void setFoodItemId(Long foodItemId) {
        this.foodItemId = foodItemId;
    }

    public String getFoodItemName() {
        return foodItemName;
    }

    public void setFoodItemName(String foodItemName) {
        this.foodItemName = foodItemName;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public RiskLevel getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(RiskLevel riskLevel) {
        this.riskLevel = riskLevel;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
        if (this.titleEn == null) {
            this.titleEn = title;
        }
    }

    public String getTitleEn() {
        return titleEn != null ? titleEn : title;
    }

    public void setTitleEn(String titleEn) {
        this.titleEn = titleEn;
        if (this.title == null) {
            this.title = titleEn;
        }
    }

    public String getTitleMy() {
        return titleMy;
    }

    public void setTitleMy(String titleMy) {
        this.titleMy = titleMy;
    }

    public String getTitle(String lang) {
        if ("mm".equalsIgnoreCase(lang) || "my".equalsIgnoreCase(lang)) {
            return (titleMy != null && !titleMy.isEmpty()) ? titleMy : getTitleEn();
        }
        return getTitleEn();
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
        if (this.descriptionEn == null) {
            this.descriptionEn = description;
        }
    }

    public String getDescriptionEn() {
        return descriptionEn != null ? descriptionEn : description;
    }

    public void setDescriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
        if (this.description == null) {
            this.description = descriptionEn;
        }
    }

    public String getDescriptionMy() {
        return descriptionMy;
    }

    public void setDescriptionMy(String descriptionMy) {
        this.descriptionMy = descriptionMy;
    }

    public String getDescription(String lang) {
        if ("mm".equalsIgnoreCase(lang) || "my".equalsIgnoreCase(lang)) {
            return (descriptionMy != null && !descriptionMy.isEmpty()) ? descriptionMy : getDescriptionEn();
        }
        return getDescriptionEn();
    }

    public String getReasoningDetails() {
        return reasoningDetails;
    }

    public void setReasoningDetails(String reasoningDetails) {
        this.reasoningDetails = reasoningDetails;
        if (this.reasoningDetailsEn == null) {
            this.reasoningDetailsEn = reasoningDetails;
        }
    }

    public String getReasoningDetailsEn() {
        return reasoningDetailsEn != null ? reasoningDetailsEn : reasoningDetails;
    }

    public void setReasoningDetailsEn(String reasoningDetailsEn) {
        this.reasoningDetailsEn = reasoningDetailsEn;
        if (this.reasoningDetails == null) {
            this.reasoningDetails = reasoningDetailsEn;
        }
    }

    public String getReasoningDetailsMy() {
        return reasoningDetailsMy;
    }

    public void setReasoningDetailsMy(String reasoningDetailsMy) {
        this.reasoningDetailsMy = reasoningDetailsMy;
    }

    public String getReasoningDetails(String lang) {
        if ("mm".equalsIgnoreCase(lang) || "my".equalsIgnoreCase(lang)) {
            return (reasoningDetailsMy != null && !reasoningDetailsMy.isEmpty()) ? reasoningDetailsMy : getReasoningDetailsEn();
        }
        return getReasoningDetailsEn();
    }

    public BigDecimal getEstimatedSavings() {
        return estimatedSavings;
    }

    public void setEstimatedSavings(BigDecimal estimatedSavings) {
        this.estimatedSavings = estimatedSavings;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
