package com.foodwasteai.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Model representing actionable mitigation recommendations generated by SWI-Prolog expert system.
 */
public class Recommendation implements Serializable {
    private static final long serialVersionUID = 1L;

    public enum Category {
        URGENT,
        IMPORTANT,
        OPTIMIZATION,
        REDISTRIBUTION
    }

    public enum RiskLevel {
        LOW,
        MEDIUM,
        HIGH
    }

    public enum Status {
        PENDING,
        ACCEPTED,
        DISMISSED,
        COMPLETED
    }

    private Long id;
    private Long foodItemId;
    private String foodItemName; // Joined
    private Category category;
    private RiskLevel riskLevel;
    private String title;
    private String description;
    private String reasoningDetails;
    private BigDecimal estimatedSavings;
    private Status status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Recommendation() {}

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFoodItemId() {
        return foodItemId;
    }

    public void setFoodItemId(Long foodItemId) {
        this.foodItemId = foodItemId;
    }

    public String getFoodItemName() {
        return foodItemName;
    }

    public void setFoodItemName(String foodItemName) {
        this.foodItemName = foodItemName;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public RiskLevel getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(RiskLevel riskLevel) {
        this.riskLevel = riskLevel;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getReasoningDetails() {
        return reasoningDetails;
    }

    public void setReasoningDetails(String reasoningDetails) {
        this.reasoningDetails = reasoningDetails;
    }

    public BigDecimal getEstimatedSavings() {
        return estimatedSavings;
    }

    public void setEstimatedSavings(BigDecimal estimatedSavings) {
        this.estimatedSavings = estimatedSavings;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
