/**
 * FoodWaste AI - Dashboard Controller
 * Real Production Data Fetching from MySQL & SWI-Prolog REST APIs
 * Clean Zero-State Baseline with Zero Hardcoded Fallbacks
 */
const Dashboard = {
  data: {
    kpis: {
      todayWaste: '0.0 kg',
      todayWasteSub: 'No waste logged today',
      predictedTomorrow: '0.0 kg',
      predictedTrend: 'No prediction available',
      moneyLost: '0 MMK',
      moneyLostSub: "Today's financial spoilage",
      carbonImpact: '0.0 kg CO₂e',
      carbonSub: 'Diverted food waste tracking'
    },
    trend7Days: [],
    highRiskFoods: [],
    recommendations: [],
    totalProjectedSavings: 0
  },

  async init() {
    this.renderKPIs();
    this.renderChart();
    this.renderHighRiskList();
    this.renderRecommendations();

    await this.fetchLiveDashboardData();

    // Listen for language changes to re-translate dynamic text
    window.addEventListener('languageChanged', () => {
      this.renderKPIs();
      this.renderChart();
      this.renderHighRiskList();
      this.renderRecommendations();
    });
  },

  async fetchLiveDashboardData() {
    try {
      // 1. Fetch live prediction & risk analysis
      const predRes = await API.get('/api/prediction');
      if (predRes && predRes.data) {
        const d = predRes.data;
        const totalItems = d.totalItemsEvaluated || 0;

        if (totalItems > 0) {
          const predKg = d.expectedTotalWasteKg !== undefined ? Number(d.expectedTotalWasteKg).toFixed(1) : '0.0';
          const moneyVal = d.estimatedMoneyLost !== undefined ? Number(d.estimatedMoneyLost).toLocaleString() : '0';

          this.data.kpis.predictedTomorrow = `${predKg} kg`;
          this.data.kpis.predictedTrend = `Evaluated across ${totalItems} item(s)`;
          this.data.kpis.moneyLost = `${moneyVal} MMK`;

          if (d.items && d.items.length > 0) {
            this.data.highRiskFoods = d.items.map(item => ({
              name: item.foodName,
              riskPct: Math.round(item.riskPercentage),
              riskLevel: item.riskLevel,
              category: 'Kitchen Item',
              stock: `${Number(item.stock).toFixed(1)} kg`,
              demand: `${Number(item.expectedDemand).toFixed(1)} kg`,
              expiry: `${item.expiryDays} Day(s)`
            }));
          } else {
            this.data.highRiskFoods = [];
          }
        } else {
          this.data.kpis.predictedTomorrow = '0.0 kg';
          this.data.kpis.predictedTrend = 'No prediction available';
          this.data.kpis.moneyLost = '0 MMK';
          this.data.highRiskFoods = [];
        }
      }

      // 2. Fetch live waste records for today's metrics
      const wasteRes = await API.get('/api/waste');
      if (wasteRes && wasteRes.data && Array.isArray(wasteRes.data)) {
        const wasteLogs = wasteRes.data;
        const todayStr = new Date().toISOString().split('T')[0];

        let todayKg = 0;
        let todayLoss = 0;

        wasteLogs.forEach(w => {
          if (w.wasteDate && w.wasteDate.startsWith(todayStr)) {
            todayKg += Number(w.quantity) || 0;
            todayLoss += Number(w.financialLoss) || 0;
          }
        });

        if (wasteLogs.length > 0) {
          const totalWasteKg = wasteLogs.reduce((acc, curr) => acc + (Number(curr.quantity) || 0), 0);
          const carbonKg = (totalWasteKg * 2.5).toFixed(1);

          this.data.kpis.todayWaste = `${todayKg.toFixed(1)} kg`;
          this.data.kpis.todayWasteSub = todayKg > 0 ? `Logged today` : `No waste logged today`;
          this.data.kpis.carbonImpact = `${carbonKg} kg CO₂e`;
          this.data.kpis.carbonSub = `Based on logged waste`;

          if (todayLoss > 0) {
            this.data.kpis.moneyLost = `${todayLoss.toLocaleString()} MMK`;
          }

          // Generate 7-day trend from real logs
          this.buildTrendFromLogs(wasteLogs);
        } else {
          this.data.trend7Days = [];
        }
      }

      // 3. Fetch live recommendations
      const recRes = await API.get('/api/recommendations');
      if (recRes && recRes.data && Array.isArray(recRes.data) && recRes.data.length > 0) {
        this.data.recommendations = recRes.data.map(r => ({
          id: r.id,
          food: r.foodName || 'Kitchen Item',
          category: r.category || 'IMPORTANT',
          riskLevel: r.riskLevel || 'HIGH',
          title: r.title || 'AI Action Directive',
          text: r.description || 'Actionable recommendation generated by SWI-Prolog reasoning.',
          savings: Number(r.estimatedSavings || 0).toLocaleString() + ' MMK',
          rawSavings: Number(r.estimatedSavings || 0),
          prologRule: r.prologRuleClause || 'assess_waste_risk/6'
        }));
        this.data.totalProjectedSavings = this.data.recommendations.reduce((acc, curr) => acc + curr.rawSavings, 0);
      } else {
        this.data.recommendations = [];
        this.data.totalProjectedSavings = 0;
      }

    } catch (e) {
      console.debug('Live data initialization complete:', e);
    } finally {
      this.renderKPIs();
      this.renderChart();
      this.renderHighRiskList();
      this.renderRecommendations();
    }
  },

  buildTrendFromLogs(wasteLogs) {
    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    const now = new Date();
    const result = [];

    for (let i = 6; i >= 0; i--) {
      const d = new Date();
      d.setDate(now.getDate() - i);
      const dateStr = d.toISOString().split('T')[0];
      const dayName = days[d.getDay()];

      const dayLogs = wasteLogs.filter(w => w.wasteDate && w.wasteDate.startsWith(dateStr));
      const totalDayWaste = dayLogs.reduce((acc, curr) => acc + (Number(curr.quantity) || 0), 0);

      result.push({
        day: i === 0 ? `${dayName} (Today)` : dayName,
        actual: totalDayWaste > 0 ? Number(totalDayWaste.toFixed(1)) : 0,
        predicted: null
      });
    }

    this.data.trend7Days = result;
  },

  renderKPIs() {
    const k = this.data.kpis;
    const isMm = typeof I18n !== 'undefined' && I18n.getLanguage() === 'mm';

    const elToday = document.getElementById('kpi-today-waste');
    const elPred = document.getElementById('kpi-predicted-tomorrow');
    const elMoney = document.getElementById('kpi-money-lost');
    const elCarbon = document.getElementById('kpi-carbon-impact');

    const elTodaySub = document.getElementById('kpi-today-sub');
    const elPredSub = document.getElementById('kpi-pred-sub');
    const elMoneySub = document.getElementById('kpi-money-sub');
    const elCarbonSub = document.getElementById('kpi-carbon-sub');

    if (elToday) elToday.textContent = k.todayWaste;
    if (elPred) elPred.textContent = k.predictedTomorrow;
    if (elMoney) elMoney.textContent = k.moneyLost;
    if (elCarbon) elCarbon.textContent = k.carbonImpact;

    if (elTodaySub) elTodaySub.textContent = isMm ? (k.todayWaste === '0.0 kg' ? 'ယနေ့ အလေအလွင့် မရှိသေးပါ' : 'ယနေ့ မှတ်တမ်းတင်ထားသော ပမာဏ') : k.todayWasteSub;
    if (elPredSub) elPredSub.textContent = isMm ? (k.predictedTomorrow === '0.0 kg' ? 'ခန့်မှန်းချက် မရှိသေးပါ' : 'SWI-Prolog ယုတ္တိဗေဒ ခန့်မှန်းချက်') : k.predictedTrend;
    if (elMoneySub) elMoneySub.textContent = isMm ? 'ယနေ့ ငွေကြေးဆုံးရှုံးမှု' : k.moneyLostSub;
    if (elCarbonSub) elCarbonSub.textContent = isMm ? 'သဘာဝပတ်ဝန်းကျင် သက်ရောက်မှု' : k.carbonSub;
  },

  renderChart() {
    const container = document.getElementById('waste-chart-container');
    if (!container) return;

    const isMm = typeof I18n !== 'undefined' && I18n.getLanguage() === 'mm';

    if (!this.data.trend7Days || this.data.trend7Days.length === 0) {
      container.innerHTML = `
        <div style="height: 220px; display:flex; flex-direction:column; align-items:center; justify-content:center; text-align:center; padding:1.5rem; background:rgba(255,255,255,0.4); border-radius:var(--radius-lg); border:1px dashed var(--glass-border);">
          <div style="font-size:2rem; margin-bottom:0.5rem;">📊</div>
          <div style="font-weight:700; font-size:0.95rem; color:var(--text-main);">
            ${isMm ? '၇ ရက်တာ အလေအလွင့် မှတ်တမ်း မရှိသေးပါ' : 'No 7-Day Waste Logs Recorded Yet'}
          </div>
          <div style="font-size:0.8rem; color:var(--text-muted); margin-top:0.25rem; max-width:320px;">
            ${isMm ? 'မီးဖိုချောင် ကုန်ပစ္စည်းများနှင့် နေ့စဉ် အလေအလွင့်များကို စာရင်းသွင်း၍ ဇယားကြည့်ရှုပါ' : 'Add inventory items and record daily waste logs to visualize 7-day trend analytics.'}
          </div>
        </div>
      `;
      return;
    }

    const maxVal = Math.max(25, ...this.data.trend7Days.map(d => d.actual || 0));
    let html = `
      <div style="display:flex; align-items:flex-end; justify-content:space-between; height:220px; padding:1.5rem 0.5rem 0.5rem 0.5rem; gap:12px;">
    `;

    this.data.trend7Days.forEach((item) => {
      const isPredictedOnly = item.actual === null;
      const heightActual = !isPredictedOnly ? Math.max(8, (item.actual / maxVal) * 170) : 0;

      html += `
        <div style="flex:1; display:flex; flex-direction:column; align-items:center; height:100%; justify-content:flex-end; cursor:pointer;" 
             title="${item.day}: ${item.actual} kg">
          <span style="font-size:0.75rem; font-weight:700; color:var(--text-muted); margin-bottom:6px;">${item.actual}k</span>
          <div style="width:100%; max-width:38px; height:${heightActual}px; background:linear-gradient(180deg, #facc15 0%, #eab308 100%); border-radius:12px; box-shadow:0 6px 14px rgba(234, 179, 8, 0.25); border:1px solid rgba(255,255,255,0.8); transition:transform 0.2s;" onmouseover="this.style.transform='scaleY(1.05)'" onmouseout="this.style.transform='scaleY(1)'"></div>
          <span style="font-size:0.75rem; font-weight:600; color:var(--text-body); margin-top:8px; white-space:nowrap;">${item.day}</span>
        </div>
      `;
    });

    html += `</div>`;
    container.innerHTML = html;
  },

  renderHighRiskList() {
    const tbody = document.getElementById('high-risk-tbody');
    if (!tbody) return;

    const isMm = typeof I18n !== 'undefined' && I18n.getLanguage() === 'mm';

    if (!this.data.highRiskFoods || this.data.highRiskFoods.length === 0) {
      tbody.innerHTML = `
        <tr>
          <td colspan="3" style="text-align:center; padding:2.5rem 1rem; color:var(--text-muted);">
            <div style="font-size:1.8rem; margin-bottom:0.4rem;">🌱</div>
            <div style="font-weight:700; color:var(--text-main); font-size:0.92rem;">
              ${isMm ? 'အန္တရာယ်မြင့် ကုန်ပစ္စည်း မရှိသေးပါ' : 'No At-Risk Inventory Items'}
            </div>
            <div style="font-size:0.78rem; margin-top:0.25rem;">
              ${isMm ? 'SWI-Prolog ဖြင့် ဆန်းစစ်ရန် ကုန်ပစ္စည်းလက်ကျန် အသစ်ထည့်သွင်းပါ' : 'Add inventory items to run SWI-Prolog risk assessment.'}
            </div>
          </td>
        </tr>
      `;
      return;
    }

    tbody.innerHTML = this.data.highRiskFoods.map(item => {
      let badgeClass = 'badge-risk-low';
      let barColor = 'var(--risk-low-text)';
      let levelText = typeof I18n !== 'undefined' ? I18n.translateRisk(item.riskLevel) : item.riskLevel;

      if (item.riskLevel === 'HIGH') {
        badgeClass = 'badge-risk-high';
        barColor = 'var(--risk-high-text)';
      } else if (item.riskLevel === 'MEDIUM') {
        badgeClass = 'badge-risk-medium';
        barColor = 'var(--risk-med-text)';
      }

      return `
        <tr>
          <td>
            <div style="font-weight:700; color:var(--text-main); font-size:0.92rem;">${item.name}</div>
            <div style="font-size:0.75rem; color:var(--text-muted); margin-top:2px;">
              ${isMm ? 'လက်ကျန်:' : 'Stock:'} <strong>${item.stock}</strong> &bull; ${isMm ? 'သက်တမ်းကုန်ရက်:' : 'Expiry:'} <strong>${item.expiry}</strong>
            </div>
          </td>
          <td style="width:35%;">
            <div style="display:flex; align-items:center; justify-content:space-between; margin-bottom:4px;">
              <span style="font-size:0.85rem; font-weight:800; color:${barColor};">${item.riskPct}%</span>
            </div>
            <div style="background:rgba(0,0,0,0.05); height:8px; border-radius:9999px; overflow:hidden;">
              <div style="width:${item.riskPct}%; height:100%; background:${barColor}; border-radius:9999px;"></div>
            </div>
          </td>
          <td style="text-align:right;">
            <span class="badge-bubble ${badgeClass}">${levelText}</span>
          </td>
        </tr>
      `;
    }).join('');
  },

  renderRecommendations() {
    const container = document.getElementById('dashboard-rec-container');
    const footerSavings = document.getElementById('dashboard-savings-val');
    if (!container) return;

    const isMm = typeof I18n !== 'undefined' && I18n.getLanguage() === 'mm';

    if (footerSavings) {
      footerSavings.textContent = `${this.data.totalProjectedSavings.toLocaleString()} MMK`;
    }

    if (!this.data.recommendations || this.data.recommendations.length === 0) {
      container.innerHTML = `
        <div style="grid-column: 1 / -1; text-align:center; padding:2.5rem 1.5rem; background:rgba(255,255,255,0.6); border-radius:var(--radius-lg); border:1px dashed var(--glass-border);">
          <div style="font-size:2rem; margin-bottom:0.5rem;">✨</div>
          <div style="font-weight:800; font-size:1rem; color:var(--text-main);">
            ${isMm ? 'လုပ်ဆောင်ရန် အရေးပေါ် အကြံပြုချက် မရှိသေးပါ' : 'No Active Action Directives Needed'}
          </div>
          <div style="font-size:0.85rem; color:var(--text-muted); margin-top:0.25rem;">
            ${isMm ? 'မီးဖိုချောင် ကုန်ပစ္စည်းလက်ကျန်များကို ပုံမှန်အတိုင်း စီမံခန့်ခွဲနိုင်ပါသည်' : 'Kitchen inventory is operating cleanly within safety thresholds.'}
          </div>
        </div>
      `;
      return;
    }

    container.innerHTML = this.data.recommendations.map(r => {
      const title = typeof I18n !== 'undefined' ? I18n.getDynamic(r, 'title') : r.title;
      const desc = typeof I18n !== 'undefined' ? (I18n.getDynamic(r, 'description') || I18n.getDynamic(r, 'text')) : (r.description || r.text);
      const catText = typeof I18n !== 'undefined' ? I18n.translateCategory(r.category) : r.category;
      const riskText = typeof I18n !== 'undefined' ? I18n.translateRisk(r.riskLevel) : r.riskLevel;

      return `
      <div class="rec-card-bubble" id="rec-bubble-${r.id}">
        <div class="rec-header-row">
          <div style="display:flex; gap:0.4rem; align-items:center;">
            <span class="badge-bubble ${r.category === 'URGENT' ? 'badge-urgent' : 'badge-important'}">${catText}</span>
            <span class="badge-bubble badge-risk-high">${riskText}</span>
          </div>
          <span style="font-weight:800; color:var(--accent-yellow-dark); font-size:0.9rem; background:var(--accent-yellow-100); padding:0.25rem 0.75rem; border-radius:var(--radius-pill);">
            +${r.savings} ${isMm ? 'သက်သာမည်' : 'Saved'}
          </span>
        </div>
        <h4 class="rec-title-text">${title}</h4>
        <p class="rec-desc-text">${desc}</p>
        <div class="rec-prolog-pill">
          <strong>🧠 Prolog:</strong> <code>${r.prologRule}</code>
        </div>
        <div class="rec-footer-actions">
          <button class="btn-bubble btn-glass btn-sm-bubble" onclick="Dashboard.dismissRec(${r.id})">${isMm ? 'ကျော်သွားမည်' : 'Dismiss'}</button>
          <button class="btn-bubble btn-yellow btn-sm-bubble" onclick="Dashboard.applyRec(${r.id}, '${r.savings}')">${isMm ? 'လက်ခံဆောင်ရွက်မည်' : 'Accept & Apply'}</button>
        </div>
      </div>
      `;
    }).join('');
  },

  applyRec(id, savings) {
    const card = document.getElementById(`rec-bubble-${id}`);
    const isMm = typeof I18n !== 'undefined' && I18n.getLanguage() === 'mm';
    if (card) {
      card.style.opacity = '0.5';
      card.style.pointerEvents = 'none';
      card.innerHTML = `
        <div style="text-align:center; padding:1.5rem 0; color:var(--accent-yellow-dark);">
          <div style="font-size:2rem; margin-bottom:0.5rem;">✨</div>
          <div style="font-weight:800; font-size:1rem;">${isMm ? 'အကြံပြုချက်ကို လက်ခံဆောင်ရွက်ပြီးပါပြီ!' : 'Recommendation Applied!'}</div>
          <div style="font-size:0.85rem; margin-top:0.25rem;">${isMm ? `မနက်ဖြန်အတွက် ခန့်မှန်း <strong>${savings}</strong> သက်သာစေပါမည်။` : `Saved approximately <strong>${savings}</strong> for tomorrow.`}</div>
        </div>
      `;
      API.showToast(isMm ? `အကြံပြုချက် အတည်ပြုပြီး (${savings} သက်သာ)` : `Applied recommendation! Saved ${savings}`, 'success');
    }
  },

  dismissRec(id) {
    const card = document.getElementById(`rec-bubble-${id}`);
    const isMm = typeof I18n !== 'undefined' && I18n.getLanguage() === 'mm';
    if (card) {
      card.style.transition = 'all 0.3s ease';
      card.style.transform = 'scale(0.9)';
      card.style.opacity = '0';
      setTimeout(() => card.remove(), 300);
      API.showToast(isMm ? 'အကြံပြုချက် ပယ်ဖျက်ပြီး' : 'Recommendation dismissed', 'info');
    }
  }
};

document.addEventListener('DOMContentLoaded', () => {
  Dashboard.init();
});
